### ISSUE TITLE
No Cocoapod

### ISSUE THREAD

**Issue by prafsoni** [apple/swift-nio-ssl#115]
I am having trouble finding Cocoapod. Is it available under a different name?

**Comment by prafsoni** [comment]
@weissi any ideas?

**Comment by weissi** [comment]
@prafsoni yes. So for NIO1 we couldn’t make a Cocoapod because we depended on the system’s openssl (which iOS doesn’t have). For NIO 2 we don’t so a Cocoapod would be possible but there’s lots of code that needs to be build in C/C++/Assembly/Swift and I’m not sure if cocoapod can build that.

On top of this, we recommend for people on iOS to use SwiftNIOTransportServices (see https://github.com/apple/swift-nio-transport-services) and with that you very likely won’t need NIOSSL because it can be done by NIOTransportServices (through Network.framework).

If you manage to build a pod we might consider using it though. What iOS versions do you need to target? Would NIOTransportServices be an option for you?

**Comment by prafsoni** [comment]
@weissi Thanks for the information.  I am targeting iOS 10+ and totally get your points, I am using `swift-nio-ssl` to support SSL on Linux. For Apple platforms, I am planning to use transport-services where its available and URLSession elsewhere. 

Since there is not pod available my pod specs was failing. Currently, I have worked my way around using `#if canimport(NIOSSL)` blocks. This brings me to my next question, What is the recommended lib for SSL on Linux? I assume `swift-nio-ssl`.

As far as packaging goes I attempted to build a pod for NIO2 but was not successful ran into weird errors beyond my noob `pod` skills 😎

**Comment by weissi** [comment]
@prafsoni Unfortunately, NIOTransportServices (because it's based on Network.framework) requires iOS 12+ so you will need `swift-nio-ssl` for at least your iOS 10 & 11 users anyway...

Correct, on Linux (and everywhere else where either Network.framwork isn't available or isn't powerful enough) `swift-nio-ssl` is the recommended way. It doesn't have any system extra system dependencies but it must be built somehow.

You mentioned you were trying to build a pod for NIO2 but we publish those already. The pod name is [SwiftNIO](https://cocoapods.org/pods/SwiftNIO) and at the time of writing it's available in version 2.3.0, so definitely NIO 2. We have pods for NIO, NIOExtras, NIOTransportServices, just not NIOSSL (because historically it was impossible and these days just nobody has done the work to build a pod builder script for NIOSSL yet).

**Comment by prafsoni** [comment]
@weissi By NIO2 pod, I meant `swift-nio-ssl` compatible with NIO2. I believe a pod will make life a lot easier for people supporting older platforms

**Comment by weissi** [comment]
> @weissi By NIO2 pod, I meant `swift-nio-ssl` compatible with NIO2. I believe a pod will make life a lot easier for people supporting older platforms

Would you like to try and see if you can produce a working pod? As soon as you have something that works, we can turn it into a generator script like in the other NIO repos and then we'd be happy to publish it.

As an alternative: If you can use Xcode 11, you can just add the NIOSSL using Xcode 11's Swift Package support and you wouldn't need to use Cocoapods at all.

**Comment by Lukasa** [comment]
There is indeed a cocoapod now.
