### ISSUE TITLE
error:  uncleanShutdown when call channel.close().wait()

### ISSUE THREAD

**Issue by woodcrust** [apple/swift-nio-ssl#18]
I use this code for connecting to server with supports TLS protocol

```swift

.... another code ....

var configuration = TLSConfiguration.forClient(
    certificateVerification: CertificateVerification.none
)
let sslContext = try SSLContext(configuration: configuration)
let sslHandler = try OpenSSLClientHandler(context: sslContext, serverHostname: "localhost")

let bootstrap = ClientBootstrap(group: group)
    .channelOption(ChannelOptions.socket(SocketOptionLevel(SOL_SOCKET), SO_REUSEADDR), value: 1)
    
    .channelInitializer { channel in
        return channel.pipeline.add(handler: sslHandler).then() {
                channel.pipeline.add(handler: ChatHandler())
        }
}


.... another code ....


let channel = try { () -> Channel in
        switch connectTarget {
        case .ip(let host, let port):
            return try bootstrap.connect(host: host, port: port).wait()
        case .unixDomainSocket(let path):
            return try bootstrap.connect(unixDomainSocketPath: path).wait()
        }
}()
```

and if I sended message to server I will get error:  uncleanShutdown when I want close this channel : 

```swift
let line = "some message"
var buffer  = channel.allocator.buffer(capacity: line.utf8.count)
buffer.write(string: line)

// send message
channel.writeAndFlush(buffer).wait()
// and close channel
try! channel.close().wait() // returned error:  uncleanShutdown
```

and if close this channel without send message to server its will be normal close...
please tell me, what I am doing wrong ?

**Comment by Lukasa** [comment]
Nothing, inherently. 

The uncleanShutdown error means that the remote peer did not send a TLS CLOSE_NOTIFY message. This error is fired because the absence of that message *could* mean that there is an attacker performing a length-truncation attack on your connection, where they inject a TCP FIN. If your protocol provides higher level knowledge that the data has not been truncated, then this error can be ignored.

Alternatively, the server could be updated to send CLOSE_NOTIFY.

**Comment by woodcrust** [comment]
thank you for your prompt response
