### ISSUE TITLE
TLS 1.3 with PSK using SwiftNIO Transport Services and Network framework

### ISSUE THREAD

**Issue by kv30** [apple/swift-nio-ssl#309]
Using SwiftNIO Transport Services, we were able to connect to server using PSK for the version TLS 1.2. We used API like 
`sec_protocol_options_add_pre_shared_key and sec_protocol_options_set_pre_shared_key_selection_block.`

Whereas **_same APIs  do not connect for TLS 1.3 PSK_** with server. We are setting tls min and max version through
```
sec_protocol_options_set_min_tls_protocol_version(securityProtocolOptions, .TLSv13) sec_protocol_options_set_max_tls_protocol_version(securityProtocolOptions, .TLSv13)
```

This results in **OPENSSL_internal:NO_SUPPORTED_VERSIONS_ENABLED** and also the cipher suites we set through `sec_protocol_options_append_tls_ciphersuite(tlsOptions.securityProtocolOptions,.CHACHA20_POLY1305_SHA256)` does not get reflected in Wireshark too. 

And also if we change `min_tls_protocol_version` to .TLSv12, tls1.2 connection happens _**but the cipher suites**_ we set are **not at all added** in the list of  cipher suites in Wireshark.

Any suggestions to get PSK connection successfully with TLS 1.3?

**Comment by Lukasa** [comment]
This issue is not a SwiftNIO issue, nor is it a SwiftNIO SSL issue. You’d be best placed to raise this issue on the forums at developer.apple.com, where someone will be able to assist you with the configuration of the Network.framework security layer.

swift-nio-transport-services does not manually adjust the TLS configuration, so your changes are the only ones that affect it.

**Comment by agnosticdev** [comment]
Posting the [link here](https://developer.apple.com/forums/thread/688508) for continuity purposes.  Thanks again.
