### ISSUE TITLE
Multiple commands produce

### ISSUE THREAD

**Issue by Nahatakyan** [apple/swift-nio-ssl#364]
Hi. I am trying to use this library in my app, but when I install this library (version 2.19.0), the application is not building: `Multiple commands produce`. Here is the link to the screen recording:
https://drive.google.com/file/d/1MgmXBD-AO_CELhenZ6PpLoLoPf0NUjMp/view?usp=sharing
In the video you can see, that library fetching takes a long (I clear the cache of SPM).

XCode 13.3.1 (13E500a), MacOS 12.3.1 (21E258), Apple M1 Pro

**Comment by Lukasa** [comment]
Your compiler issues are caused by adding the swift-nio-ssl executables as dependencies when you include the package. When you add the swift-nio-ssl package, only check `NIOSSL` as a dependency: do not click `NIOTLSServer` or `NIOSSLHTTP1Client`.

The long library fetch is the result of the swift-nio repository being very large, as it contains our documentation. This is something we know about and plan to resolve, but is not easy to fix.
