### ISSUE TITLE
Incomplete definition of type 'struct bio_st'

### ISSUE THREAD

**Issue by elbuki** [apple/swift-nio-ssl#377]
Hi there! 👋 

I was setting up a project with the [SlackKit library](https://github.com/pvzig/SlackKit) that has a dependency to `swift-nio-ssl` and when building an error in `shims.c` appears with the following:
<img width="1436" alt="Screen Shot 2022-07-02 at 4 51 45 PM" src="https://user-images.githubusercontent.com/7534831/177018205-bedf6c75-3d37-4c7f-b51d-f5f42cbcc597.png">
This is my development stack just in case:
```
Xcode 13.4.1
macOS 12.4
SlackKit 4.8.0
Libressl stable 3.5.3 installed with Homebrew 3.4.11
MacBook Air 2020 M1
```
Related issue: https://github.com/pvzig/SlackKit/issues/211

**Comment by Lukasa** [comment]
Unfortunately you appear to be using v1 of this library, which exited support some time ago. SwiftNIO SSL 2.x has been the mainline release since March 2019, so the v1 series is receiving security fixes only. I recommend encouraging SlackKit to adopt newer versions of their web socket stack, which appears to be the thing dragging in the old copy of SwiftNIO SSL.
